platform :ios, '9.0'
target 'spotmeapp' do
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
pod 'GoogleMaps'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end